// const fs = require('fs');
const notes = require('./notes.js');
// const validator = require('validator');
const log = require('./chalking');
// fs.writeFileSync("notes.txt", "This text is written with NODE JS!");
// fs.appendFileSync('notes.txt', 'By kushagra singh for note apps');
const getNotes = notes.getNotes();
console.log(getNotes);
// console.log(validator.isEmail('ksk@gmail.com'));
log('The app is running fine....', 'success');
log('Found a vulnerability', 'warning');
log('Working on it....');
log('Your app crashed shutting down......', 'error');
